#!/bin/bash


for i in $(seq 1 1 10); do
    (time topdown.py -l3 -nd  -f ./nn filelist_4 " -r 5 -lat 30 -lng 90") >> time_topdown.txt 2>&1
    (time ./nn filelist_4 -r 5 -lat 30 -lng 90) >> time_native.txt 2>&1
done
topdown.py -l3 -nd -os scan_file.txt -o results_topdown.txt -f ./nn filelist_4 " -r 5 -lat 30 -lng 90"