#!/bin/bash
# > result.txt


for i in $(seq 1 1 10); do
    (time topdown.py -f ./pathfinder 100000 100 20 -l3 -nd) >> time_topdown.txt 2>&1

    (time ./pathfinder 100000 100 20) >> time_native.txt 2>&1
done
 topdown.py -f ./pathfinder 100000 100 20 -l3 -nd -os scan_file.txt -o results_topdown.txt