#!/bin/bash


for i in $(seq 1 1 10); do
    (time topdown.py -f ./needle 2048 10 -l3 -nd) >> time_topdown.txt 2>&1 
    (time ./needle 2048 10 -l3) >> time_native.txt 2>&1
done
topdown.py -f ./needle 2048 10 -l3 -nd -os scan_file.txt -o results_topdown.txt


