#!/bin/bash
#topdown.py -l3 -nd -os scan_file_file.txt -o results_topdown_file.txt -f gaussian "../../../../../data/gaussian/matrix4.txt"
#topdown.py -l3 -nd -os scan_file_16.txt -o results_topdown_16.txt -f gaussian "-s 16"
# es el de la linea 2

for i in $(seq 1 1 10); do
    (time topdown.py -l3 -nd -f gaussian "-s 16") >> time_topdown.txt 2>&1
    (time ./gaussian -s 16) >> time_native.txt 2>&1
done
topdown.py -l3 -nd -os scan_file_16.txt -o results_topdown_16.txt -f gaussian "-s 16"