#!/bin/bash
#topdown.py -l3 -nd -os scan_file.txt -o results_topdown.txt -f ./hotspot 512 2 2 $HOME/data/hotspot/temp_512 $HOME/data/hotspot/power_512 output.out
#./hotspot 512 2 2 $HOME/data/hotspot/temp_512 $HOME/data/hotspot/power_512 output.out

for i in $(seq 1 1 10); do
    (time topdown.py -l3 -nd -f ./hotspot 512 2 2 $HOME/data/hotspot/temp_512 $HOME/data/hotspot/power_512 output.out) >> time_topdown.txt 2>&1
    (time ./hotspot 512 2 2 $HOME/data/hotspot/temp_512 $HOME/data/hotspot/power_512 output.out) >> time_native.txt 2>&1
done
 topdown.py -l3 -nd -os scan_file.txt -o results_topdown.txt -f ./hotspot 512 2 2 $HOME/data/hotspot/temp_512 $HOME/data/hotspot/power_512 output.out