#!/bin/bash

for i in $(seq 1 1 10); do
    (time topdown.py -l3 -nd -f "./lavaMD -boxes1d 10") >> time_topdown.txt 2>&1
    (time ./lavaMD -boxes1d 10) >> time_native.txt 2>&1
done
topdown.py -l3 -nd -os scan_file.txt -o results_topdown.txt -f "./lavaMD -boxes1d 10"
