#!/bin/bash


for i in $(seq 1 1 10); do
    (time topdown.py -f ./sc_gpu 10 20 256 65536 65536 1000 none output.txt 1 -l3 -nd) >> time_topdown.txt 2>&1
    (time ./sc_gpu 10 20 256 65536 65536 1000 none output.txt 1) >> time_native.txt 2>&1
done
topdown.py -f ./sc_gpu 10 20 256 65536 65536 1000 none output.txt 1 -l3 -nd -os scan_file.txt -o results_topdown.txt