#!/bin/bash


for i in $(seq 1 1 10); do
    (time topdown.py -l3 -nd -f ./pavle ../../../../../data/huffman/test1024_H2.206587175259.in) >> time_topdown.txt 2>&1
    (time ./pavle ../../../../../data/huffman/test1024_H2.206587175259.in) >> time_native.txt 2>&1
done
topdown.py -l3 -nd -os scan_file.txt -o results_topdown.txt -f ./pavle ../../../../../data/huffman/test1024_H2.206587175259.in